# PATH: backend/render.yaml
services:
  - type: web
    name: ecolojia-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      NODE_VERSION: 18
